language: python

matrix:
  include:
  - os: osx
    language: generic
    env:
    - JTV_PY_VER="2.7.14"
  - os: osx
    language: generic
    env:
    - JTV_PY_VER="3.5.5"
  - os: osx
    language: generic
    env:
    - JTV_PY_VER="3.6.5"
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.5'
  - os: linux
    python: '3.6'

branches:
  only:
  - master
  - dev

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade pyenv; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install $JTV_PY_VER; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p /Users/travis/.pyenv/versions/$JTV_PY_VER/bin/python; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
install:
- pip install coveralls
script:
- make test
- coveralls

jobs:
  include:
  - stage: Deploy
    python: '3.6'
    script: skip
    deploy:
      provider: pypi
      user: jtvsoftwares
      distributions: 'bdist_wheel --universal'
      on:
        branch: master
      password:
        secure: sJdREfTuNbFcmNrPExpSatOUd8a3p9heC9ipJPEXRjVG88J0O9Pvl335m8ZnKU4YtdeAIyiselG6RK+e4QoEegTwKX1QCedFRpxxUYMnolIQ1TC1nyDx7XmFyRQD2NabfjFbV16pBIDgdou4JHj4rutX9uKIdh7T18JycQPyMF+6++M1vwJ3/mFx5pZB+klzl4p61WQ1sBeMpADWMg7hD8C9URcSLbjthrGglSXyMKZK0mkiR1Ehdth9pPx2Ylz54YQ7LHHdJveDI0hMSfl5u8JvTYGuHKaZU9M0/rl72VLtuOApm7HMlcFl1dv6bQfLZxutE79ugZvj2+t2htka41fArwPuoYeFVjdqWlQwVmS+udiy3JoHTSBaF9kUaDsUkjdehITjRmgy9YQ3WYL8+tOqZxkPyjVHTBlFjHanecSegT5YtjpwGacbX5fT8bpteUABr045sPzM2JPrHQrbiOIVrFvcV0peoFXXdZTKfpInxskynQKli+6vcGqEOvC6Y6mJcmi3rQHSll7n0lcZmSnwhuzujGHSYSvjPiIoEHEHQuhlP0Iz2rMK/e81eWUn8hcLUf+xGXFbgzQgDguwTvsR0Ztb/Si3yijdEMBCXkZRlgVWZDScEZVcvdXIF9m+cU513UdF1eCFKeUmgLfAZa9pwrzN/EitG2je9fxooq0=
