language: python

matrix:
  include:
  - os: osx
    language: generic
    env:
    - JTV_PY_VER="2.7.14"
  - os: osx
    language: generic
    env:
    - JTV_PY_VER="3.5.5"
  - os: osx
    language: generic
    env:
    - JTV_PY_VER="3.6.5"

before_install:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install pyenv; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv install $JTV_PY_VER; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pyenv global $JTV_PY_VER; fi
install:
- which pip
- which python
script:
- python --version
