language: python
python:
- '2.7'
- '3.5'
- '3.6'
branches:
  only:
  - master
  - dev
os:
- linux
install:
- pip install coveralls
script:
- make test
- coveralls

jobs:
  include:
  - stage: Deploy
    python: '3.6'
    script: skip
    deploy:
      provider: pypi
      user: jtvsoftwares
      distributions: 'bdist_wheel --universal'
      on:
        branch: master
      password:
        secure: sJdREfTuNbFcmNrPExpSatOUd8a3p9heC9ipJPEXRjVG88J0O9Pvl335m8ZnKU4YtdeAIyiselG6RK+e4QoEegTwKX1QCedFRpxxUYMnolIQ1TC1nyDx7XmFyRQD2NabfjFbV16pBIDgdou4JHj4rutX9uKIdh7T18JycQPyMF+6++M1vwJ3/mFx5pZB+klzl4p61WQ1sBeMpADWMg7hD8C9URcSLbjthrGglSXyMKZK0mkiR1Ehdth9pPx2Ylz54YQ7LHHdJveDI0hMSfl5u8JvTYGuHKaZU9M0/rl72VLtuOApm7HMlcFl1dv6bQfLZxutE79ugZvj2+t2htka41fArwPuoYeFVjdqWlQwVmS+udiy3JoHTSBaF9kUaDsUkjdehITjRmgy9YQ3WYL8+tOqZxkPyjVHTBlFjHanecSegT5YtjpwGacbX5fT8bpteUABr045sPzM2JPrHQrbiOIVrFvcV0peoFXXdZTKfpInxskynQKli+6vcGqEOvC6Y6mJcmi3rQHSll7n0lcZmSnwhuzujGHSYSvjPiIoEHEHQuhlP0Iz2rMK/e81eWUn8hcLUf+xGXFbgzQgDguwTvsR0Ztb/Si3yijdEMBCXkZRlgVWZDScEZVcvdXIF9m+cU513UdF1eCFKeUmgLfAZa9pwrzN/EitG2je9fxooq0=
